### ISSUE TITLE
[tokens] fetching token failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by hafx** [zedeus/nitter#1008]
Hello, 

I have issues to deploy my own instance of nitter. 
2 problems : 
- [tokens] fetching token failed: Resource temporarily unavailable
- Additional info: Name does not resolve

Any idea what am I supposed to do ?

**Setup**
- ubuntu 22.04
- docker rootless :24.0.1

**logs nitter**
```
Starting Nitter at https://mydomain.tld
Connected to Redis at nitter-redis:6379
[tokens] fetching token failed: Resource temporarily unavailable
Additional info: Name does not resolve
[tokens] fetching tokens paused, resuming in 30 minutes
INFO Jester is making jokes at http://0.0.0.0:8080
```
**logs nitter-redis**
```
1:C 03 Sep 2023 18:21:43.270 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 03 Sep 2023 18:21:43.270 * Redis version=7.2.0, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 03 Sep 2023 18:21:43.270 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 03 Sep 2023 18:21:43.271 * monotonic clock: POSIX clock_gettime
1:M 03 Sep 2023 18:21:43.271 * Running mode=standalone, port=6379.
1:M 03 Sep 2023 18:21:43.272 * Server initialized
1:M 03 Sep 2023 18:21:43.272 * Loading RDB produced by version 7.2.0
1:M 03 Sep 2023 18:21:43.272 * RDB age 1 seconds
1:M 03 Sep 2023 18:21:43.272 * RDB memory usage when created 0.92 Mb
1:M 03 Sep 2023 18:21:43.272 * Done loading RDB, keys loaded: 6, keys expired: 0.
1:M 03 Sep 2023 18:21:43.272 * DB loaded from disk: 0.000 seconds
1:M 03 Sep 2023 18:21:43.272 * Ready to accept connections tcp
```

nitter.conf
```
[Server]
hostname = "domain.tld"  # for generating links, change this to your own domain/ip
title = "nitter"
address = "0.0.0.0"
port = 8080
https = true  # disable to enable cookies when not using https
httpMaxConnections = 100
staticDir = "./public"

[Cache]
listMinutes = 240  # how long to cache list info (not the tweets, so keep it high)
rssMinutes = 10  # how long to cache rss queries
redisHost = "nitter-redis"  # Change to "nitter-redis" if using docker-compose
redisPort = 6379
redisPassword = ""
redisConnections = 20  # minimum open connections in pool
redisMaxConnections = 30
# new connections are opened when none are available, but if the pool size
# goes above this, they're closed when released. don't worry about this unless
# you receive tons of requests per second

[Config]
hmacKey = "secretkey"  # random key for cryptographic signing of video urls
base64Media = false  # use base64 encoding for proxied media urls
enableRSS = true  # set this to false to disable RSS feeds
enableDebug = yes  # enable request logs and debug endpoints (/.tokens)
proxy = ""  # http/https url, SOCKS proxies are not supported
proxyAuth = ""
tokenCount = 10
# minimum amount of usable tokens. tokens are used to authorize API requests,
# but they expire after ~1 hour, and have a limit of 500 requests per endpoint.
# the limits reset every 15 minutes, and the pool is filled up so there's
# always at least `tokenCount` usable tokens. only increase this if you receive
# major bursts all the time and don't have a rate limiting setup via e.g. nginx

# Change default preferences here, see src/prefs_impl.nim for a complete list
[Preferences]
theme = "Nitter"
replaceTwitter = "domain.tld"
replaceYouTube = "piped.video"
replaceReddit = "teddit.net"
proxyVideos = true
hlsPlayback = false
infiniteScroll = false
```

docker-compose.yaml
```
version: "3"

services:

  nitter:
    image: zedeus/nitter:latest
    container_name: nitter
    ports:
            - "127.0.0.1:8080:8080" # Replace with "8080:8080" if you don't use a reverse proxy
    volumes:
      - /nitter/nitter.conf:/src/nitter.conf:Z,ro
    depends_on:
      - nitter-redis
        # restart: unless-stopped
        #healthcheck:
        #test: wget -nv --tries=1 --spider http://127.0.0.1:8082/Jack/status/20 || exit 1
        #interval: 30s
        #timeout: 5s
        #retries: 2
    user: "998:998"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - /nitter/nitter-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  nitter-redis:
```
Thx
