### ISSUE TITLE
[Question] Is there a way to use a twitter acc in combination with nitter (or an alternative twitter front end using your twitter login)

### ISSUE THREAD

**Issue by back-lacking** [zedeus/nitter#1195]
what the question says
wondering if there is a way to use nitter with a twitter account? i have an account i dont care about and would like to use that to view the occasional tweet using the front end. ik that using an twitter acc to look at tweets using nitter defeats the point of nitter existing
if there isnt, is there an alternative service or nitter fork that allows this?

**Comment by pin-grid-array** [comment]
Yes, there is a way. Actually, that's the _only_ way left to use Nitter.

I recently learned that that's exact how https://github.com/PrivacyDevel/nitter is able to continue to functioning these days. It's also how they have been able to display age-restricted content.

**Comment by back-lacking** [comment]
@pin-grid-array i see. Can i know how this is done?

**Comment by pin-grid-array** [comment]
@back-lacking I actually don't know how. I'm just a former ordinary Nitter user and it's beyond my expertise. Ask in that fork.

A while ago I collected [various instructions](https://github.com/zedeus/nitter/issues/983#issuecomment-1944095658) from people who tried setting up their own instance using a Twitter account, but I don't know if any of that still applies.

(I just noticed that there are a bunch of typos in my previous reply to you. Sorry about that!)

**Comment by brokewq** [comment]
@back-lacking hey dude did you find any way to use nitter with a twitter ac ?

**Comment by doffn** [comment]
> @back-lacking hey dude did you find any way to use nitter with a twitter ac ?

you can use other ways aside from nitter. If you are planning to use ur twitter account. I can share you hwhat i use

**Comment by back-lacking** [comment]
@doffn if you do have a 3rd party viewer, send it in. Perferebly one that can be deployed on docker. 
On a side note, on android i use an app called quacker. Its on fdroid.

**Comment by doffn** [comment]
> @doffn if you do have a 3rd party viewer, send it in. Perferebly one that can be deployed on docker. On a side note, on android i use an app called quacker. Its on fdroid.

@back-lacking sorry for the late response. I used two methods to scrape tweets:
1. Using *[twitter-api-client](https://github.com/trevorhobenshield/twitter-api-client)* : require `cto` and `auth_token` from your cookies. You can direcly tweet, dm, follow , like and scrape tweets using this. this require the latest python version. It can also scrape multiple account at once.
2. Using *[tweety](https://github.com/mahrtayyab/tweety)*: this requires the full session.  i use this to scrape tweets. I didnot find any inherent way to scrape multiple account at once.

After getting the data do what ever you like with it. becare full on the rate limit. You can avoid this by using multiple account.

**Comment by rinaldi6109** [comment]
> > @back-lacking hey dude did you find any way to use nitter with a twitter ac ?
> 
> you can use other ways aside from nitter. If you are planning to use ur twitter account. I can share you hwhat i use

I'm interested. Can you tell me how? Thank you.

**Comment by back-lacking** [comment]
@rinaldi6109 im using a fork made by privacydevel. Its been posted earlier by pingridarray. I can later post a docker compose that i got working.

**Comment by codeiimon** [comment]
@back-lacking If you could post the docker compose you got working that would be awesome. I'm very interested.

**Comment by back-lacking** [comment]
@codeiimon edited this compose to have it work in most environments. 
```yaml
version: "3"
services:
  nitter:
    image: ghcr.io/privacydevel/nitter:master
    container_name: nitter
    ports:
      - "8080:8080" # Replace with "8080:8080" if you don't use a reverse proxy
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
      - ./guest_accounts.json:/src/guest_accounts.json:ro
    depends_on:
      - nitter-redis
    restart: unless-stopped
    networks:
      - nitter
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    user: 998:998
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    hostname: nitter-redis
    ports:
      - 6379
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - nitter
    volumes:
      - nitter-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    user: 999:1000
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
volumes:
  nitter-redis: null
networks:
  nitter:
```
