### ISSUE TITLE
Docker image goes into startup loop

### ISSUE THREAD

**Issue by Wyrrrd** [zedeus/nitter#179]
Since several days ago, my self-hosted docker nitter instance goes into startup loop.

Log repeats over and over:
`/bin/sh: ./start.sh: not found`

I normally use a labeled volume mapped to `/src`, but nitter creates another volume mapped to `/data` now (which is empty).

**Comment by setenforce0** [comment]
Is start.sh in the src directory? the /data volume is part of the redis image to allow persistent storage.

**Comment by Wyrrrd** [comment]
start.sh was missing, even on container recreation. After manually adding it to the volume, the container started as usual.

**Comment by setenforce0** [comment]
I can't reproduce, can you give me steps to reproduce please?

**Comment by Wyrrrd** [comment]
I set it up using docker-compose:

```
version: "2"
services:
  nitter:
    container_name: nitter
    image: zedeus/nitter:latest
    restart: unless-stopped
    volumes:
      - nitter_data:/src
```

Then left it to be updated by [watchtower](https://github.com/containrrr/watchtower).

The recreation of the container didn't have an effect, because I reused the volume, which had `start.sh` already missing.

Seems like the issue is caused by my setup, sorry to bother you.
