### ISSUE TITLE
Odd issue with only Nitter giving connection refused for IPv6 behind Traefik v1 with docker.

### ISSUE THREAD

**Issue by jtagcat** [zedeus/nitter#329]
Many tens of services all work fine, on both IPv4 and IPv6, however Nitter does not.

This is likely not the fault of Traefik, I'd suspect it to not be a problem in other configurations, where all traffic from the reverse proxy is forwarded to an IPv4 address.

`nitter.conf`:
```
[Server]
address = "0.0.0.0" # Changing this to anything really doesn't seem to affect anything. Can leave empty as well.
port = 8080
https = true  # disable to enable cookies when not using https
staticDir = "./public"
hostname = "nitter.net"
...
```

`docker-compose.yml`:
```
version: '3'

networks:
  web_proxy:
    external: true

services:
  traefik:
    image: 'traefik:1.7-alpine'
    container_name: traefik
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik.toml:/traefik.toml:ro'
      - './acme.json:/acme.json:rw'
    ports:
      - '80:80'
      - '443:443'
    network_mode: web_proxy
    
  nitter:
    image: 'zedeus/nitter'
    volumes:
      - ./nitter.conf:/src/nitter.conf:ro
    depends_on:
      - traefik
    labels:
      - traefik.frontend.rule=Host:nitter.net
      - traefik.port=8080
    networks:
      - web_proxy
 
  ipv6workshere:
    image: httpd:alpine
    depends_on:
      - traefik
    labels:
      - traefik.frontend.rule=Host:ipv6.nitter.net
      - traefik.port=80
    networks:
      - web_proxy
```
To show, that the config is otherwise fine, there's a httpd instance added at the end.

For full replication, you also need an (empty) acme.json file, `chmod 600`, and a `traefik.toml`:
```
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"

      [entryPoints.https.redirect]
      regex = "^https://www.(.*)"
      replacement = "https://$1"
      permanent = true
      [entryPoints.https.tls]
      compress = true

[acme]
email = "user@domain.tld"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
watch = true
network = "web_proxy"
```

As a debugging measure, adding:
```
    ports:
      - 5555:8080
```
Makes the container accessible over ipv4, but not over ipv6. When doing the same with httpd, it's available on both ipv4 and ipv6.
```
curl -6 http://nitter.net:5555
curl: (7) Failed to connect to nitter.net port 5555: Connection refused
```
