### ISSUE TITLE
User preferences in `nitter.conf` doesnt seem to apply

### ISSUE THREAD

**Issue by ms-jpq** [zedeus/nitter#358]
This happens for me under the latest docker image.

I know the conf file is mounted correctly, because I can customize the page title:

But what ever I put under `[Preferences]` seem to be moot.

![图片](https://user-images.githubusercontent.com/50598611/110852676-8506f480-8267-11eb-8d4c-1f07bb1e4d99.png)

Here is my full settings, the `{{ xxx }}` are placeholders that I template over during runtime, which I also verified that they work correctly.

```toml
[Server]
https = true
title = "🐓"
hostname = "twitter.{{ DC_HOST }}"

[Config]
hmacKey = "{{ NITTER_KEY }}"

# Change default preferences here, see src/prefs_impl.nim for a complete list
[Preferences]
replaceTwitter = "twitter.{{ DC_HOST }}"
replaceYouTube = "youtube.{{ DC_HOST }}"

proxyVideos = false
hlsPlayback = true

theme = "Auto"
infiniteScroll = true

```
