### ISSUE TITLE
redis not working

### ISSUE THREAD

**Issue by Latrolage** [zedeus/nitter#446]
I'm getting problems with whatever program redis is.
when running start.sh i get
```
nohup: appending output to 'nohup.out'
nohup: failed to run command 'redis-server': No such file or directory
```
and then nitter fails to connect to redis

Want I wanted was for nitter to be run on local port 6900 and then have my nginx thing direct traffic of a domain to this localhost port.

I'm confused to whether I'm supposed to use 
```
docker run -v $(pwd)/nitter.conf:/src/nitter.conf -d -p 6900:8080 zedeus/nitter:latest
```
to start the server or start.sh

**Comment by Latrolage** [comment]
was not aware that redis is a separate program

**Comment by Myzel394** [comment]
@Latrolage How did you solve this?

**Comment by zedeus** [comment]
By running Redis separately

**Comment by Myzel394** [comment]
@zedeus Is there documentation available for this? If not, what env variables do I need to set for Nitter?

**Comment by zedeus** [comment]
Redis just has to be run with default settings by installing it and running redis-server. Nitter's config file needs to have the right port and such for Redis to connect to it, but the defaults should be fine.

**Comment by Myzel394** [comment]
@zedeus Could you help me out here? I'm trying to setup redis, but I always get this error:

```
Starting Nitter at http://nitter.net
Failed to connect to Redis.
```

my docker-compose.yml

```
 nitter-redis:
        container_name: nitter-redis
        image: redis:alpine
        restart: on-failure:5
        networks:
            - nitter_db
        command: redis-server --save 60 1 --loglevel warning --requirepass password
        healthcheck:
            test: redis-cli ping
            interval: 30s
            timeout: 5s
            retries: 2

    nitter:
        container_name: nitter
        image: quay.io/unixfox/nitter
        restart: on-failure:5
        depends_on:
            - nitter-redis
        networks:
            - nitter
            - nitter_db
        volumes:
            - ./nitter.conf:/src/nitter.conf:ro
        healthcheck:
            test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
            interval: 30s
            timeout: 5s
            retries: 2
```
