### ISSUE TITLE
ARM64 image via docker-compose doesn't work on Raspberry Pi 4

### ISSUE THREAD

**Issue by cinetube** [zedeus/nitter#487]
<img width="644" alt="nitter not working" src="https://user-images.githubusercontent.com/23441775/147538416-6174f8ba-9519-445a-9341-a8ba85f041c2.png">

**Comment by zedeus** [comment]
How was Nitter compiled? What OS/distro is this? How are you running it?

**Comment by cinetube** [comment]
> How was Nitter compiled? What OS/distro is this? How are you running it?

I am using ubuntu server on raspberry pi. 

I am using the latest Nitter image that was pushed to docker hub within last 30 minutes.

**Comment by zedeus** [comment]
It works fine for me when I run `redis-server` and `docker run -d --network host zedeus/nitter:latest`
What commands are you using?

**Comment by cinetube** [comment]
> It works fine for me when I run `redis-server` and `docker run -d --network host zedeus/nitter:latest` What commands are you using?

Here is my docker compose:

```
version: '3.3'
services:
    nitter:
        image: zedeus/nitter:latest
        container_name: nitter
        volumes:
            - /mnt/nitter/nitter.conf:/src/nitter.conf
        ports:
            - 8039:8080
        restart: unless-stopped 
```
