### ISSUE TITLE
docker-compose: 502 Bad Gateway

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [zedeus/nitter#535]
Everything seems running fine in docker but for some reason i can't access to website because i get bad getaway

docker-compose logs:
```
Attaching to nitter, nitter-redis
nitter          | 2022-01-30T14:25:37.204156725Z Starting Nitter at http://nitter.esmailelbob.xyz
nitter          | 2022-01-30T14:25:37.209319895Z Connected to Redis at nitter-redis:6379
nitter-redis    | 2022-01-30T14:25:31.776426427Z 1:C 30 Jan 2022 14:25:31.776 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
nitter-redis    | 2022-01-30T14:25:31.776458527Z 1:C 30 Jan 2022 14:25:31.776 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
nitter-redis    | 2022-01-30T14:25:31.776464002Z 1:C 30 Jan 2022 14:25:31.776 # Configuration loaded
nitter-redis    | 2022-01-30T14:25:31.777266354Z 1:M 30 Jan 2022 14:25:31.777 # Server initialized
```
docker-compose file:
```
version: "3"

services:

  nitter:
    image: zedeus/nitter:latest
    container_name: nitter
    ports:
      - "0.0.0.0:4040:8080" # Replace with "8080:8080" if you don't use a reverse proxy
    volumes:
      - ./nitter.conf:/src/nitter.conf:ro
    depends_on:
      - nitter-redis
    restart: unless-stopped

  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-redis:/data
    restart: unless-stopped

volumes:
  nitter-redis:
```
nitter.conf:
```
[Server]
address = "0.0.0.0"
port = 4040
https = false  # disable to enable cookies when not using https
httpMaxConnections = 100
staticDir = "./public"
title = "nitter"
hostname = "nitter.esmailelbob.xyz"

[Cache]
listMinutes = 240  # how long to cache list info (not the tweets, so keep it high)
rssMinutes = 10  # how long to cache rss queries
redisHost = "nitter-redis" # Change to "nitter-redis" if using docker-compose
redisPort = 6379
redisPassword = ""
redisConnections = 20  # connection pool size
redisMaxConnections = 30
# max, new connections are opened when none are available, but if the pool size
# goes above this, they're closed when released. don't worry about this unless
# you receive tons of requests per second

[Config]
hmacKey = "secretkey"  # random key for cryptographic signing of video urls
base64Media = false  # use base64 encoding for proxied media urls
enableRSS = true  # set this to false to disable RSS feeds
enableDebug = false  # enable request logs and debug endpoints
proxy = ""  # http/https url, SOCKS proxies are not supported
proxyAuth = ""
tokenCount = 10
# minimum amount of usable tokens. tokens are used to authorize API requests,
# but they expire after ~1 hour, and have a limit of 187 requests.
# the limit gets reset every 15 minutes, and the pool is filled up so there's
# always at least $tokenCount usable tokens. again, only increase this if
# you receive major bursts all the time

# Change default preferences here, see src/prefs_impl.nim for a complete list
[Preferences]
theme = "Nitter"
replaceTwitter = "nitter.net"
replaceYouTube = "piped.kavin.rocks"
replaceReddit = "teddit.net"
replaceInstagram = ""
proxyVideos = true
hlsPlayback = false
infiniteScroll = false
```
my nginx file for nitter:
```
server {
        server_name nitter.esmailelbob.xyz ;
       location / {
               include /etc/nginx/reverse-proxy.conf;
               proxy_pass http://0.0.0.0:4040/;
       }
        add_header Onion-Location http://nitter.lqs5fjmajyp7rvp4qvyubwofzi6d4imua7vs237rkc4m5qogitqwrgyd.onion$request_uri;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/nitter.esmailelbob.xyz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/nitter.esmailelbob.xyz/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
        listen 127.0.0.1:80 ;
        server_name nitter.lqs5fjmajyp7rvp4qvyubwofzi6d4imua7vs237rkc4m5qogitqwrgyd.onion ;
        location / {
                       include /etc/nginx/reverse-proxy.conf;
                       proxy_pass http://0.0.0.0:8090/;
               }
}
server {
    if ($host = nitter.esmailelbob.xyz) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name nitter.esmailelbob.xyz ;

    listen [::]:80;
    listen 80;
    return 404; # managed by Certbot


}
```
I'm using debian 11 and let me know if you need more data/logs :)
