### ISSUE TITLE
Having trouble setting up docker-compose

### ISSUE THREAD

**Issue by Latrolage** [zedeus/nitter#569]
My full steps were
```
git clone https://github.com/zedeus/nitter
cd nitter
nvim ./docker-compose.yml # set ports to "127.0.0.1:3300:8080" and image to "quay.io/unixfox/nitter:latest" (i'm on arm)
cp ./nitter.example.conf nitter.conf
nvim ./nitter.conf # set hostname to my domain name and set redistHost to nitter-redis
docker-compose up -d
```

`docker logs nitter` then gives me 
```
Starting Nitter at http://nitter.net
Failed to connect to Redis.
```
What did I do wrong?

**Comment by jackyzy823** [comment]
Since you're using unixfox/nitter , you should see  docker-compose.yml under README in https://github.com/goodtiding5/docker-nitter , [Ref](https://github.com/zedeus/nitter/issues/399#issuecomment-997263495) , so you need mount ./nitter.conf to /data/nitter.conf.

**Comment by Latrolage** [comment]
Yes, I managed to stumble upon that and it's working now. My new docker-compose is: 
```
version: "3"

services:

  nitter:
    image: quay.io/unixfox/nitter:latest
    container_name: nitter
    restart: always
    depends_on:
      - redis
    volumes:
      - ./data/nitter:/data
    ports:
      - "127.0.0.1:3300:8080"
    environment:
      - REDIS_HOST="redis"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
```
