### ISSUE TITLE
nitter.conf is resetting on start

### ISSUE THREAD

**Issue by Latrolage** [zedeus/nitter#743]
the nitter.conf file always resets to the default whenever the container starts, whether it be through `docker-compose up` or `docker stop nitter && docker start nitter`

This is my docker-compose the redis.conf file is 
```
version: "3"
 
services:
 
  nitter:
    image: quay.io/unixfox/nitter:latest
    container_name: nitter
    restart: always
    depends_on:
      - redis
    volumes:
      - ./data/nitter:/data
    ports:
      - "127.0.0.1:3300:8080"
    environment:
            - REDIS_HOST="redis"
 
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./data/redis:/data
      - ./data/redis:/usr/local/etc/redis/redis.conf:rw
```

```
❯ docker-compose up --build --no-deps --force-recreate --remove-orphans
Recreating redis ... done
Recreating nitter ... done
Attaching to redis, nitter
redis     | 1:C 08 Dec 2022 10:07:14.454 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis     | 1:C 08 Dec 2022 10:07:14.454 # Redis version=7.0.2, bits=64, commit=00000000, modified=0, pid=1, just started
redis     | 1:C 08 Dec 2022 10:07:14.454 # Configuration loaded
nitter    | Starting Nitter at http://nitter.net
redis     | 1:M 08 Dec 2022 10:07:14.455 * monotonic clock: POSIX clock_gettime
redis     | 1:M 08 Dec 2022 10:07:14.456 * Running mode=standalone, port=6379.
redis     | 1:M 08 Dec 2022 10:07:14.456 # Server initialized
redis     | 1:M 08 Dec 2022 10:07:14.459 * Loading RDB produced by version 7.0.2
redis     | 1:M 08 Dec 2022 10:07:14.459 * RDB age 6 seconds
redis     | 1:M 08 Dec 2022 10:07:14.459 * RDB memory usage when created 0.97 Mb
redis     | 1:M 08 Dec 2022 10:07:14.459 * Done loading RDB, keys loaded: 12, keys expired: 0.
redis     | 1:M 08 Dec 2022 10:07:14.459 * DB loaded from disk: 0.000 seconds
redis     | 1:M 08 Dec 2022 10:07:14.459 * Ready to accept connections
nitter    | Connected to Redis at redis:6379
```
