### ISSUE TITLE
Add fullscreen modal image

### ISSUE THREAD

**Issue by honnip** [zedeus/nitter#755]
It's annoying to open an image in a new tab whenever I want to see a clearer one. So it would be nice to display larger image in a modal when I click the image.

**Comment by honnip** [comment]
```html
<div class="attachment image">
  <a class="still-image" href="#randomId">
    <img src="/pic/media/random.jpg?name=small" alt="">
  </a>
  <div id="randomId" class="modal">
    <img src="/pic/media/ramdom.jpg" alt="">
  </div>
</div>
```
```scss
.modal {
  // lots of styles

  visibility: hidden;
  &:target {
    visibility: visible;
  }
}
```
In this workaround without JavaScript, there is a problem of requesting a larger image even if I do not click the image.
