### ISSUE TITLE
Can't get self-hosted instance to work

### ISSUE THREAD

**Issue by harkfujow** [zedeus/nitter#933]
As the title says. I simply can't get it up and running. I keep getting the error:

Starting Nitter at http://nitter.net
Failed to connect to Redis.

I'm using a single board computer with an Intel chip (Zimaboard). I'm running other services on it (e.g. Wikiless), but I just can't figure this one out.

Here is my docker-compose:

```
version: '3.3'

services:
  app:
    image: zedeus/nitter:latest
    container_name: nitter
    restart: always
    depends_on:
      - redis
    volumes:
      - /DATA/AppData/nitter:/data
    ports:
      - "8086:8080"
    environment:
      - REDIS_HOST="redis"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - /DATA/AppData/nitter/redis:/data
``` 

Any guidance as to where I'm messing up would be greatly appreciated.
